name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 01 - Checkout
        uses: actions/checkout@v2

      - name: 02 - Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: code3tech/centos
          flavor: |
            latest=auto
            prefix=
            suffix=

      - name: 03 - Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 04 - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}